name: Docker Image CI for GHCR

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build and Push
        run: |
          docker build . --tag ghcr.io/${{ github.repository_owner }}/docker-xserver-ghcr:latest
          docker push ghcr.io/${{ github.repository_owner }}/docker-xserver-ghcr:latest