name: Docker Image CI for GHCR

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Push
        run: |
          docker login --username itshimoo --password ${{secrets.GHCR_PAT}}
          docker build . --tag ghcr.io/itshimoo/docker-xserver-ghcr:latest
          docker push ghcr.io/itshimoo/docker-xserver-ghcr:latest
