name: Docker Image Push to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  push:
    name: Push Docker Image to Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Pull, tag, and push Docker Image
        run: |
          TEMP_IMAGE=ghcr.io/${{ github.repository_owner }}/docker-xserver-ghcr:temp
          LATEST_IMAGE=ghcr.io/${{ github.repository_owner }}/docker-xserver-ghcr:latest
          docker pull $TEMP_IMAGE
          docker tag $TEMP_IMAGE $LATEST_IMAGE
          docker push $LATEST_IMAGE
